document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'Content-Security-Policy\' content=\'upgrade-insecure-requests\'>");
document.writeln("    <title>monsuta tag 敵人/活動</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../../a.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../enemy.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'boxA\'>");
document.writeln("        <header class=\'header\'>");
document.writeln("            <input type=\'radio\' name=\'A\' id=\'a\'>");
document.writeln("            <input type=\'radio\' name=\'A\' id=\'n\'>");
document.writeln("            <input type=\'radio\' name=\'A\' id=\'s\'>");
document.writeln("            <div class=\'top\'>");
document.writeln("                <label for=\'a\' class=\'top-name\'>敌人</label>");
document.writeln("                <label for=\'n\' class=\'top-name\'>活动</label>");
document.writeln("                <label for=\'s\' class=\'top-name\'>兽神</label>");
document.writeln("                <div class=\'top-name\'>");
document.writeln("                    <a href=\'../../index.html\'>返回主页</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <nav class=\'cheack\'>");
document.writeln("                <div class=\'che che1\'>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss1.html\'><span>完全無欠デカイオー</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss2.html\'><span>双角型キングスライム</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss3.html\'><span>忠臣の騎士シスイ</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss4.html\'><span>魔導巡洋艦カッツォ</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss5.html\'><span>歴戦の覇者Gデカイオー</span></a>");
document.writeln("                </div>");
document.writeln("                <div class=\'che che2\'>");
document.writeln("                    <a");
document.writeln("                        href=\'https://bambooght.github.io/monsuta.tag/enemy/Activity/Activity1.html\'><span>「狙われたホルスタイン」</span></a>");
document.writeln("                </div>");
document.writeln("                <div class=\'che che3\'>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/Beast God/Vivi Vache.html\' class=\'BG\'>");
document.writeln("                        <img");
document.writeln("                            src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcYVU*5af0BsyGVARHRli19k23EY57Z31IJuwXmW1*JkXa5xCM5LCDKwBliGtiAxaU8oM6JubG59TV.yLehj4u6w!/r\'>");
document.writeln("                        <img src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcfs8rWOnyP2w6VsWfW6ozomlhH0S4gIPNGUPn3XaHf3RoRGD7uphK6X471dPohiUmpAZPWUUyqhpW663h7YSLUY!/r\'");
document.writeln("                            alt=\'\'>");
document.writeln("                        <p>ヴィヴィヴァーチェ</p>");
document.writeln("                    </a>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/Beast God/Needhog.html\' class=\'BG\'>");
document.writeln("                        <img");
document.writeln("                            src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcUAj07pdG43wxx7oBx4321CFUwSr2W1qjzU3VmMMF*Ms4ZpJ5DZ9z*XR1QgBl2yqhKMK.ajAA65YhBDtkcjNbp4!/r\'>");
document.writeln("                        <img src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcfs8rWOnyP2w6VsWfW6ozomlhH0S4gIPNGUPn3XaHf3RoRGD7uphK6X471dPohiUmpAZPWUUyqhpW663h7YSLUY!/r\'");
document.writeln("                            alt=\'\'>");
document.writeln("                        <p>ニーズホッグ</p>");
document.writeln("                    </a>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/Beast God/Faro Luce.html\' class=\'BG\'>");
document.writeln("                        <img");
document.writeln("                            src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcZpr0cz2e2S1M5Y*nfTFLT5gV8X4J0*OfIy84aPFgWfIGQOjdnzVE3MD*uwxaPC.8U2ctO8doMvCN8HQRjO7818!/r\'>");
document.writeln("                        <img src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcfs8rWOnyP2w6VsWfW6ozomlhH0S4gIPNGUPn3XaHf3RoRGD7uphK6X471dPohiUmpAZPWUUyqhpW663h7YSLUY!/r\'");
document.writeln("                            alt=\'\'>");
document.writeln("                        <p>ファロルーチェ</p>");
document.writeln("                    </a>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/Beast God/Pazuzu.html\' class=\'BG\'>");
document.writeln("                        <img");
document.writeln("                            src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcZ4h5mpbT79MqOHnn8t3YEORC4U4EBDJFQbUihU0iYg.xfvpIbnswpNt4rtwpmeXX*fa4ZkARnArVmqQwy5kjW8!/r\'>");
document.writeln("                        <img src=\'http://r.photo.store.qq.com/psc?/V50pxDAU02i4IM2FNvvt2AmJbL05ZGxp/45NBuzDIW489QBoVep5mcfs8rWOnyP2w6VsWfW6ozomlhH0S4gIPNGUPn3XaHf3RoRGD7uphK6X471dPohiUmpAZPWUUyqhpW663h7YSLUY!/r\'");
document.writeln("                            alt=\'\'>");
document.writeln("                        <p>パズズ</p>");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("            </nav>");
document.writeln("        </header>");
document.writeln("    </div>");
document.writeln("    <script type=\'text/javascript\' src=\'http://lib.sinaapp.com/js/jquery/1.7.2/jquery.js\'>");
document.writeln("    </script>");
document.writeln("    <script src=\'input.js\'>");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");