document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'Content-Security-Policy\' content=\'upgrade-insecure-requests\'>");
document.writeln("    <title>monsuta tag 敵人/活動</title>");
document.writeln("    <link rel=\'stylesheet\' href=\'../../a.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../enemy.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <div class=\'boxA\'>");
document.writeln("        <header class=\'header\'>");
document.writeln("            <input type=\'radio\' name=\'A\' id=\'a\'>");
document.writeln("            <input type=\'radio\' name=\'A\' id=\'n\'>");
document.writeln("            <div class=\'top\'>");
document.writeln("                <label for=\'a\' class=\'top-name\'>敌人</label>");
document.writeln("                <label for=\'n\' class=\'top-name\'>活动</label>");
document.writeln("                <div class=\'top-name\'>");
document.writeln("                    <a href=\'../../index.html\'>返回主页</a>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <nav class=\'cheack\'>");
document.writeln("                <div class=\'che1\'>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss1.html\'><span>完全無欠デカイオー</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss2.html\'><span>双角型キングスライム</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss3.html\'><span>忠臣の騎士シスイ</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss4.html\'><span>魔導巡洋艦カッツォ</span></a>");
document.writeln("                    <p></p>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/boss/boss5.html\'><span>歴戦の覇者Gデカイオー</span></a>");
document.writeln("                </div>");
document.writeln("                <div class=\'che2\'>");
document.writeln("                    <a href=\'https://bambooght.github.io/monsuta.tag/enemy/Activity/Activity1.html\'><span>「狙われたホルスタイン」</span></a>");
document.writeln("                </div>");
document.writeln("            </nav>");
document.writeln("        </header>");
document.writeln("    </div>");
document.writeln("    <script type=\'text/javascript\' src=\'http://lib.sinaapp.com/js/jquery/1.7.2/jquery.js\'>");
document.writeln("    </script>");
document.writeln("    <script src=\'input.js\'>");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("");
document.writeln("</html>");